apiVersion: v1
kind: Config
clusters:
- name: "psc-cluster-rke"
  cluster:
    server: "https://rancher-psc/k8s/clusters/c-gvglk"
    certificate-authority-data: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJwekNDQ\
      VUyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQTdNUnd3R2dZRFZRUUtFeE5rZVc1aGJXbGoKY\
      kdsemRHVnVaWEl0YjNKbk1Sc3dHUVlEVlFRREV4SmtlVzVoYldsamJHbHpkR1Z1WlhJdFkyRXdIa\
      GNOTWpJdwpOakE0TVRFd016UTRXaGNOTXpJd05qQTFNVEV3TXpRNFdqQTdNUnd3R2dZRFZRUUtFe\
      E5rZVc1aGJXbGpiR2x6CmRHVnVaWEl0YjNKbk1Sc3dHUVlEVlFRREV4SmtlVzVoYldsamJHbHpkR\
      1Z1WlhJdFkyRXdXVEFUQmdjcWhrak8KUFFJQkJnZ3Foa2pPUFFNQkJ3TkNBQVNWT2lWVjlGZ0I3U\
      EsrVjlJT2dVeC9WN3BMMEdpZkFoZ01Rd09ONFFOMQpaQ1FMUHp2K29IRW1JdWJLeExFRDNPOEU1c\
      3Y3NUFha3dRTGdRSW9xMERMWW8wSXdRREFPQmdOVkhROEJBZjhFCkJBTUNBcVF3RHdZRFZSMFRBU\
      UgvQkFVd0F3RUIvekFkQmdOVkhRNEVGZ1FVckNaeER6SnljV2w4SitzcFZ5SVgKU1FoN0dGUXdDZ\
      1lJS29aSXpqMEVBd0lEU0FBd1JRSWhBTkllZ083ZVZDeXZOVGgyVVNCalpnK0JDVC9IQ3grTQpJN\
      21SQlZWbU5wYjdBaUFiaXc2QlU4cWcvVGRyNVFSWjhZVHRpbHM2TDFNT0hXYVBWYTF0YXB0VWR3P\
      T0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQ=="
- name: "psc-cluster-rke-ran-node01"
  cluster:
    server: "https://10.30.170.51:6443"
    certificate-authority-data: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM0VENDQ\
      WNtZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFTTVJBd0RnWURWUVFERXdkcmRXSmwKT\
      FdOaE1CNFhEVEl5TURZd09ESXdNemswTVZvWERUTXlNRFl3TlRJd016azBNVm93RWpFUU1BNEdBM\
      VVFQXhNSAphM1ZpWlMxallUQ0NBU0l3RFFZSktvWklodmNOQVFFQkJRQURnZ0VQQURDQ0FRb0NnZ\
      0VCQUwwY2RBZms0bFFLCjc0d1hjKzlxdGdtL2xEcXBlTGora0lVVkN5azlxMGlhNGJaUjJkYkg3T\
      GV3VEVZMndpVThwaEhaWXYrb3gvVnAKZk5Qc2ZreUtpSkNLOUFoWHBxSW5ZUjVDZ2lXQ2xLaFY1V\
      Wl4alRNcjAvK1lLVFRXUFJDRVM0MEU5dmZ2NEpWcQpFMGxnTGR6TzhjanBBV0hCL2NmbmlXTG9aY\
      XowQ25RZmd4WUJzSXJtL1FKeHdvVHBlYURueXBBNWpVbWg3OG56CmsvWlgzTGF1WHUxTDRkRzJUU\
      zRHRFlGdmVrajNZY09KZ3I0dWdsSlhxd1dtZFRwNE54bEdZVUJOd2I3WWttYjUKTEVhNVNIcE5Zd\
      VBZekU1akd6R0pTdmhMNjVTZVZibVcwc2E5VXlPSThCRklUVDBWb2ltTjUvVFAvZldkcXZlOQpOT\
      jhLczNUQjQrVUNBd0VBQWFOQ01FQXdEZ1lEVlIwUEFRSC9CQVFEQWdLa01BOEdBMVVkRXdFQi93U\
      UZNQU1CCkFmOHdIUVlEVlIwT0JCWUVGTjQ1REJsRFB5WU9PT0lMbkZkZmE0N3FxQ2dZTUEwR0NTc\
      UdTSWIzRFFFQkN3VUEKQTRJQkFRQjNnQ3QyaFhwOGJKdk03NlZPL2s0c0ZxWmVtdlFxNjZzNHRBK\
      zk0NUlwaHZrbDdvOGkxOUI5SC9Hbgo3Zlo4bERlQVlZWWhLUmFhK0NXamc5K1RiRXJMTWFBTlNHZ\
      mFiTTFSa0RXWGZTUFZRVjh6S0Vpa2pPVWZUdHpJClgrazRVaFMyNW1lSGpQRjhEYjZUY1JCTUtmc\
      FFGcWRaa2xPeXJYYW9POXVpMHBHOGI2NFdqTmhNR09CSm51d3EKUCswNjlIN1d2cVlCVzRGV2FJc\
      1BnLy9QbjlFZnJTYUNxenJhNnJYajFBY3hVSVVidGttekRvM2JxM2hxK1FOWQo2alJ1bkMrVVNST\
      i95d0RyWTdYQzR3TWR0OSttY2E5aHRDSjlWNmpiZmlSaDl5NnozdElWYVdNNjhoR3QvMnFSClNlR\
      UdmU2hxbk11NVZ3QWl2Qi9FUHdIeUcwWFYKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo="
- name: "psc-cluster-rke-ran-node02"
  cluster:
    server: "https://10.30.170.52:6443"
    certificate-authority-data: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM0VENDQ\
      WNtZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFTTVJBd0RnWURWUVFERXdkcmRXSmwKT\
      FdOaE1CNFhEVEl5TURZd09ESXdNemswTVZvWERUTXlNRFl3TlRJd016azBNVm93RWpFUU1BNEdBM\
      VVFQXhNSAphM1ZpWlMxallUQ0NBU0l3RFFZSktvWklodmNOQVFFQkJRQURnZ0VQQURDQ0FRb0NnZ\
      0VCQUwwY2RBZms0bFFLCjc0d1hjKzlxdGdtL2xEcXBlTGora0lVVkN5azlxMGlhNGJaUjJkYkg3T\
      GV3VEVZMndpVThwaEhaWXYrb3gvVnAKZk5Qc2ZreUtpSkNLOUFoWHBxSW5ZUjVDZ2lXQ2xLaFY1V\
      Wl4alRNcjAvK1lLVFRXUFJDRVM0MEU5dmZ2NEpWcQpFMGxnTGR6TzhjanBBV0hCL2NmbmlXTG9aY\
      XowQ25RZmd4WUJzSXJtL1FKeHdvVHBlYURueXBBNWpVbWg3OG56CmsvWlgzTGF1WHUxTDRkRzJUU\
      zRHRFlGdmVrajNZY09KZ3I0dWdsSlhxd1dtZFRwNE54bEdZVUJOd2I3WWttYjUKTEVhNVNIcE5Zd\
      VBZekU1akd6R0pTdmhMNjVTZVZibVcwc2E5VXlPSThCRklUVDBWb2ltTjUvVFAvZldkcXZlOQpOT\
      jhLczNUQjQrVUNBd0VBQWFOQ01FQXdEZ1lEVlIwUEFRSC9CQVFEQWdLa01BOEdBMVVkRXdFQi93U\
      UZNQU1CCkFmOHdIUVlEVlIwT0JCWUVGTjQ1REJsRFB5WU9PT0lMbkZkZmE0N3FxQ2dZTUEwR0NTc\
      UdTSWIzRFFFQkN3VUEKQTRJQkFRQjNnQ3QyaFhwOGJKdk03NlZPL2s0c0ZxWmVtdlFxNjZzNHRBK\
      zk0NUlwaHZrbDdvOGkxOUI5SC9Hbgo3Zlo4bERlQVlZWWhLUmFhK0NXamc5K1RiRXJMTWFBTlNHZ\
      mFiTTFSa0RXWGZTUFZRVjh6S0Vpa2pPVWZUdHpJClgrazRVaFMyNW1lSGpQRjhEYjZUY1JCTUtmc\
      FFGcWRaa2xPeXJYYW9POXVpMHBHOGI2NFdqTmhNR09CSm51d3EKUCswNjlIN1d2cVlCVzRGV2FJc\
      1BnLy9QbjlFZnJTYUNxenJhNnJYajFBY3hVSVVidGttekRvM2JxM2hxK1FOWQo2alJ1bkMrVVNST\
      i95d0RyWTdYQzR3TWR0OSttY2E5aHRDSjlWNmpiZmlSaDl5NnozdElWYVdNNjhoR3QvMnFSClNlR\
      UdmU2hxbk11NVZ3QWl2Qi9FUHdIeUcwWFYKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo="

users:
- name: "psc-cluster-rke"
  user:
    token: "kubeconfig-user-m5rpn2zc2f:g2xth2d7cndtfbjjbvq5zzlcqn2248xjp47rg7bcmq9pmnbwpx94pq"


contexts:
- name: "psc-cluster-rke"
  context:
    user: "psc-cluster-rke"
    cluster: "psc-cluster-rke"
- name: "psc-cluster-rke-ran-node01"
  context:
    user: "psc-cluster-rke"
    cluster: "psc-cluster-rke-ran-node01"
- name: "psc-cluster-rke-ran-node02"
  context:
    user: "psc-cluster-rke"
    cluster: "psc-cluster-rke-ran-node02"

current-context: "psc-cluster-rke"
