apiVersion: v1
kind: Pod
metadata:
  name: nginx-using-pvc
  labels:
    app: nginx-using-pvc
spec:
  volumes:
    - name: pv-any-name
      persistentVolumeClaim:
        #claimName: pv-claim-dyn-1g
        claimName: longhorn-simple-pvc
  containers:
    - name: pv-container-any-name
      image: nginx
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
        - mountPath: "/usr/share/nginx/html" #Mount point dentro do pod
          name: pv-any-name
