#É o PVC que irá definir a capacidade e criar o volume que 
#posteriormente será usado por um pod.
#Este "pedaço" volumetrico será retirado do PersistentVolume anteriormente criado 
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-claim-5g
spec:
  storageClassName: node-server-path #Deve ter o mesmo nome do SC do PV
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi #Capacidade do volume. Não pode superar o espaco disponivel no SC
