apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: color-ingress
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
        - path: /red
          pathType: Prefix
          backend:
            service:
              name: red-service
              port:
                number: 5678
        - path: /green
          pathType: Prefix
          backend:
            service:
              name: green-service
              port:
                number: 5678
        - path: /blue
          pathType: Prefix
          backend:
            service:
              name: blue-service
              port:
                number: 5678
# Neste arquivo não ha a entrada -host, dessa forma
# qualquer host/IP que chegar com /red, /green ou /blue
# sera redirecionado ao servico interno correspondente
