apiVersion: v1
kind: ConfigMap
metadata:
  name: tasa-pgr-configmap
  labels:
    app.kubernetes.io/name: tasa-pgr-name
  namespace: tasa
data:
  BD_URL: "jdbc:postgresql://postgres-service:5432/"
  BD_QUERY: "select texto from minhatabela"
---
apiVersion: v1
kind: Secret
metadata:
  name: tasa-pgr-secret
  labels:
    app.kubernetes.io/name: tasa-pgr-name
  namespace: tasa
type: Opaque
data:
  BD_USER: cG9zdGdyZXM=
  BD_PASSWORD: U2VuaGE=
